name: Continuous Integration

on:
  push:
    branches: ["**"]

jobs:
  tests:
    name: "Trello Extract Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Trello Extract dependencies
        run: |
          cd AiDo/Project/trello-extract
          python -m pip install hatch
          hatch env create
      - name: Unit Trello Extract tests
        run: |
          cd AiDo/Project/trello-extract
          hatch run test
      - name: Install Head of Product dependencies
        run: |
          cd AiDo/Project/head-of-product
          python -m pip install hatch
          hatch env create
      - name: Unit Head of Product tests
        run: |
          cd AiDo/Project/head-of-product
          hatch run test
